#!/bin/bash
#create the bridge - Br0
ip link add name br0 type bridge
ip addr add 192.168.1.50/24 dev br0
ip link set dev br0 type bridge vlan_filtering 1
#bridge vlan add vid 10 dev br0 pvid untagged self
#bridge vlan add vid 20 dev br0 pvid untagged self
#####
ip netns add ns1
ip link add name vth1 type veth peer name vth_1
ip link set vth_1 netns ns1
ip netns exec ns1 ip addr add 192.168.1.1/24 dev vth_1
ip netns exec ns1 ip route add 192.168.124.0/24 via 192.168.1.50
ip link set vth1 master br0
ip link set vth1 up
ip netns exec ns1 ip link set vth_1 up
#bridge vlan add vid 10 dev vth1 pvid untagged master
#####
ip netns add ns2
ip link add name vth2 type veth peer name vth_2
ip link set vth_2 netns ns2
ip netns exec ns2 ip addr add 192.168.1.2/24 dev vth_2
ip netns exec ns2 ip route add 192.168.124.0/24 via 192.168.1.50
ip link set vth2 master br0
ip link set vth2 up
ip netns exec ns2 ip link set vth_2 up
#bridge vlan add vid 10 dev vth2 pvid untagged master
#####
ip netns add ns3
ip link add name vth3 type veth peer name vth_3
ip link set vth_3 netns ns3
ip netns exec ns3 ip addr add 192.168.1.3/24 dev vth_3
ip netns exec ns3 ip route add 192.168.124.0/24 via 192.168.1.50
ip link set vth3 master br0
ip link set vth3 up
ip netns exec ns3 ip link set vth_3 up
#bridge vlan add vid 10 dev vth3 pvid untagged master
#####
ip netns add ns4
ip link add name vth4 type veth peer name vth_4
ip link set vth_4 netns ns4
ip netns exec ns4 ip addr add 192.168.1.4/24 dev vth_4
ip netns exec ns4 ip route add 192.168.124.0/24 via 192.168.1.50
ip link set vth4 master br0
ip link set vth4 up
ip netns exec ns4 ip link set vth_4 up
#bridge vlan add vid 10 dev vth4 pvid untagged master
######
ip netns add ns5
ip link add name vth5 type veth peer name vth_5
ip link set vth_5 netns ns5
ip netns exec ns5 ip addr add 192.168.1.5/24 dev vth_5
ip netns exec ns5 ip route add 192.168.124.0/24 via 192.168.1.50
ip link set vth5 master br0
ip link set vth5 up
ip netns exec ns5 ip link set vth_5 up
#bridge vlan add vid 10 dev vth5 pvid untagged master
######
ip netns add ns6
ip link add name vth6 type veth peer name vth_6
ip link set vth_6 netns ns6
ip netns exec ns6 ip addr add 192.168.1.6/24 dev vth_6
ip link set vth6 master br0
ip link set vth6 up
ip netns exec ns6 ip link set vth_6 up
bridge vlan add vid 20 dev vth6 pvid untagged master
#
ip netns add ns7
ip link add name vth7 type veth peer name vth_7
ip link set vth_7 netns ns7
ip netns exec ns7 ip addr add 192.168.1.7/24 dev vth_7
ip link set vth7 master br0
ip link set vth7 up
ip netns exec ns7 ip link set vth_7 up
bridge vlan add vid 20 dev vth7 pvid untagged master
#
ip netns add ns8
ip link add name vth8 type veth peer name vth_8
ip link set vth_8 netns ns8
ip netns exec ns8 ip addr add 192.168.1.8/24 dev vth_8
ip link set vth8 master br0
ip link set vth8 up
ip netns exec ns8 ip link set vth_8 up
bridge vlan add vid 20 dev vth8 pvid untagged master
####
ip netns add ns9
ip link add name vth9 type veth peer name vth_9
ip link set vth_9 netns ns9
ip netns exec ns9 ip addr add 192.168.1.9/24 dev vth_9
ip link set vth9 master br0
ip link set vth9 up
ip netns exec ns9 ip link set vth_9 up
bridge vlan add vid 20 dev vth9 pvid untagged master
####
ip link set br0 up
ip netns add ns10
ip link add name vth10 type veth peer name vth_10
ip link set vth_10 netns ns10
ip netns exec ns10 ip addr add 192.168.1.10/24 dev vth_10
ip link set vth10 master br0
ip link set vth10 up
ip netns exec ns10 ip link set vth_10 up
bridge vlan add vid 20 dev vth10 pvid untagged master
#####
ip link set br0 up

